apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: postgres-operator
resources:
  - ../../base
  - postgres-cluster.yaml

patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: postgres-operator
    spec:
      template:
        spec:
          serviceAccountName: postgres-operator
