apiVersion: v1
kind: Service
metadata:
  name: homepage
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 3000
  selector:
    app.kubernetes.io/instance: homepage
    app.kubernetes.io/name: homepage
