apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adguard
  namespace: adguard

spec:
  project: default
  source:
    repoURL: https://github.com/rayan147/ckm-infra.git
    targetRevision: HEAD
    path: operators/adguard/base
  destination:
    server: https://kubernetes.default.svc
    namespace: adguard
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
