apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-secrets-provider
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://aws.github.io/secrets-store-csi-driver-provider-aws
    targetRevision: 0.3.4 # Specify the version you want
    chart: secrets-store-csi-driver-provider-aws
    helm:
      values: |
        nodeSelector:
          kubernetes.io/os: linux
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
