apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-rbac
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rayan147/ckm-infra.git
    targetRevision: HEAD
    path: operators/postgres-operator/base/rbac
  destination:
    server: https://kubernetes.default.svc
    namespace: postgres-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
