---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

commonLabels:
  app: myapp

images:
  - name: myapp
    newName: your-registry/myapp
    newTag: latest # This will be updated by CI/CD

