# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: ckm
spec:
  selector:
    app: myapp
  type:
  ports:
    - name: myapp
      protocol:
      port: 3000
      targetPort: 3000
      nodePort: 30001
---

