apiVersion: v1
kind: PersistentVolume
metadata:
  name: adguard-conf-pv
  namespace: adguard
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeClaimPolicy: Retain
  storageClassName: longhorn
  hostPath:
    path: "/mnt/data/adguard/conf"
    type: DirectoryOrCreate
