apiVersion: v1
kind: ConfigMap
metadata:
  name: adguard-config
  namespace: adguard
data:
  AdGuardHome.yaml: |
    bind_host: 0.0.0.0
    bind_port: 3000
    users: []
    language: "en"
    dns:
      bind_host: 0.0.0.0
      port: 53
      bootstrap_dns: 
        - 1.1.1.1
        - 8.8.8.8
    tls:
      enabled: false
    log:
      enabled: true
      file: ""
      max_size: 100
      max_age: 3
      max_backups: 0
      compress: false
      local_time: false
      verbose: false
