apiVersion: v1
kind: ConfigMap
metadata:
  name: adguard-config
  namespace: adguard
  labels:
    app: adguard
data:
  AdGuardHome.yaml: |
    bind_host: 10.0.0.34
    bind_port: 3000
    beta_bind_port: 0
    users: []
    language: en
    theme: auto
    dns:
      bind_host: 10.0.0.34
      port: 53
      listen_addrs: 10.0.0.34  # Changed from array to string
      protection_enabled: true
      filtering_enabled: true
      safebrowsing_enabled: true
      safesearch_enabled: true
      querylog_enabled: true
      ratelimit: 20
      blocked_response_ttl: 10
      upstream_dns: 
        - https://dns.cloudflare.com/dns-query
        - https://dns.google/dns-query
      bootstrap_dns:
        - 1.1.1.1
        - 8.8.8.8
    tls:
      enabled: false
    filters:
      - enabled: true
        url: https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
        name: AdGuard DNS filter
        id: 1
    whitelist_filters: []
    user_rules: []
    dhcp:
      enabled: false
    log:
      file: ""
      max_backups: 0
      max_size: 100
      max_age: 3
      compress: false
      local_time: false
    filtering:
      enabled: true
      interval: 24
      blocked_services: {}  # Changed from array to object
      trusted_proxies:
        - 127.0.0.1
    querylog:
      enabled: true
      interval: 2160h
      size_memory: 1000
      ignored: []
