apiVersion: v1
kind: ConfigMap
metadata:
  name: adguard-config
  namespace: adguard
  labels:
    app: adguard
    app.kubernetes.io/name: adguard
    app.kubernetes.io/instance: adguard
data:
  AdGuardHome.yaml: |
    bind_host: 10.0.0.34
    bind_port: 3000
    beta_bind_port: 0
    users: []  # Move users to secret
    language: "en"
    theme: "auto"
    dns:
      bind_host: 10.0.0.34
      port: 53
      listen_addrs:
        - 10.0.0.34  # LoadBalancer IP
      protection_enabled: true
      filtering_enabled: true
      safebrowsing_enabled: true
      safesearch_enabled: true
      querylog_enabled: true
      ratelimit: 20
      blocked_response_ttl: 10
      upstream_dns:
        - https://dns.cloudflare.com/dns-query
        - https://dns.google/dns-query
        - 1.1.1.1
        - 8.8.8.8
      bootstrap_dns:
        - 1.1.1.1
        - 8.8.8.8
    tls:
      enabled: false
    filters:
      - enabled: true
        url: https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
        name: AdGuard DNS filter
        id: 1
      - enabled: true
        url: https://raw.githubusercontent.com/DandelionSprout/adfilt/master/GameConsoleAdblockList.txt
        name: Game Console Adblock List
        id: 2
      - enabled: true
        url: https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
        name: Windows Spy Blocker
        id: 3
      - enabled: true
        url: https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Risk/hosts
        name: Risk Hosts
        id: 4
      - enabled: true
        url: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
        name: StevenBlack Unified Hosts
        id: 5
      - enabled: true
        url: https://raw.githubusercontent.com/bigdargon/hostsVN/master/hosts
        name: hostsVN
        id: 6
      - enabled: true
        url: https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhosts.txt
        name: KADhosts
        id: 7
      - enabled: true
        url: https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt
        name: Anti-Malware Hosts
        id: 8
    whitelist_filters: []
    user_rules: []
    dhcp:
      enabled: false
    log:
      file: ""
      max_backups: 0
      max_size: 100
      max_age: 3
      compress: false
      local_time: false
    security:
      protection_enabled: true
    filtering:
      protection_enabled: true
      filtering_enabled: true
      blocked_response_ttl: 10
      safebrowsing_enabled: true
      safesearch_enabled: true
      parental_enabled: false
      safebrowsing_cache_size: 1048576
      safesearch_cache_size: 1048576
      blocked_services: []
      trusted_proxies:
        - 127.0.0.1
        - ::1
    querylog:
      enabled: true
      interval: 2160h
      size_memory: 1000
      ignored: []
