apiVersion: v1
kind: ConfigMap
metadata:
  name: adguard-config
  namespace: adguard
data:
  AdGuardHome.yaml: |
    bind_host: 0.0.0.0
    bind_port: 3000
    beta_bind_port: 0
    users: []
    auth_attempts: 5
    block_auth_min: 15
    http_proxy: ""
    language: en
    theme: auto
    debug_pprof: false
    dns:
      bind_host: 0.0.0.0
      port: 53
      protection_enabled: true
      filtering_enabled: true
      safebrowsing_enabled: true
      safesearch_enabled: true
      parental_enabled: false
      querylog_enabled: true
      ratelimit: 20
      blocked_response_ttl: 10
      bootstrap_dns:
        - 1.1.1.1
        - 8.8.8.8
