apiVersion: v1
kind: ConfigMap
metadata:
  name: adguard-config
  namespace: adguard
  labels:
    app: adguard
data:
  AdGuardHome.yaml: |
    bind_host: 10.0.0.34
    bind_port: 3000
    beta_bind_port: 0
    users: []
    language: en
    theme: auto
    dns:
      bind_host: 10.0.0.34
      port: 53
      upstream_dns:
        - https://dns.cloudflare.com/dns-query
      bootstrap_dns:
        - 1.1.1.1
        - 8.8.8.8
    tls:
      enabled: false
    http:
      address: 10.0.0.34
    log:
      file: /opt/adguardhome/work/adguard.log
      max_backups: 0
      max_size: 100
      max_age: 3
      compress: false
      local_time: false
    schema_version: 12
