apiVersion: v1
kind: ConfigMap
metadata:
  name: adguard-config
  namespace: adguard
data:
  AdGuardHome.yaml: |
    bind_host: 10.0.0.34
    bind_port: 3000
    beta_bind_port: 0
    language: en
    theme: auto
    dns:
      bind_host: 10.0.0.34
      port: 53
    tls:
      enabled: false
    log:
      file: ""
      max_backups: 0
      max_size: 100
      max_age: 3
      compress: false
      local_time: false
