apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguard-deployment
  namespace: adguard
  labels:
    app: adguard
    app.kubernetes.io/name: adguard
    app.kubernetes.io/instance: adguard
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: adguard
  template:
    metadata:
      labels:
        app: adguard
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
        - name: init-adguard-config
          image: busybox
          command:
            ["sh", "-c", "cp /config/AdGuardHome.yaml /config-destination/"]
          volumeMounts:
            - name: adguard-config
              mountPath: /config-destination
            - name: initial-config
              mountPath: /config
      containers:
        - name: adguard-home
          image: rayan147/adguardhome:nonroot
          imagePullPolicy: IfNotPresent
          env:
            - name: AGH_CONFIG
              value: /opt/adguardhome/conf/AdGuardHome.yaml
          ports:
            - containerPort: 53
              name: dns-udp
              protocol: UDP
            - containerPort: 53
              name: dns-tcp
              protocol: TCP
            - containerPort: 3000
              name: http-initial
              protocol: TCP
            - containerPort: 80
              name: http
              protocol: TCP
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          securityContext:
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              add:
                - NET_BIND_SERVICE
              drop:
                - ALL
          livenessProbe:
            httpGet:
              path: /
              port: http-initial
            initialDelaySeconds: 30
            periodSeconds: 10
          volumeMounts:
            - name: adguard-data
              mountPath: /opt/adguardhome/work
            - name: adguard-config
              mountPath: /opt/adguardhome/conf
            - name: tmp
              mountPath: /tmp
          readinessProbe:
            httpGet:
              path: /
              port: http-initial
            initialDelaySeconds: 15
            periodSeconds: 10
      volumes:
        - name: adguard-data
          persistentVolumeClaim:
            claimName: adguard-pvc
        - name: adguard-config
          persistentVolumeClaim:
            claimName: adguard-config-pvc
        - name: initial-config
          configMap:
            name: adguard-config
        - name: tmp
          emptyDir: {}
