apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguard
  namespace: adguard
  labels:
    app: adguard
spec:
  selector:
    matchLabels:
      app: adguard
  replicas: 1
  template:
    metadata:
      labels:
        app: adguard
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: adguard
          image: adguard/adguardhome:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 300Mi
          securityContext:
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              add: ["NET_BIND_SERVICE"]
              drop:
                - ALL
          ports:
            - containerPort: 53
              name: dns
              protocol: UDP
            - containerPort: 3000
              name: http-initial
            - containerPort: 80
              name: http
              protocol: TCP
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
            - name: adguard-data
              mountPath: /opt/adguardhome/work
            - name: adguard-config
              mountPath: /opt/adguardhome/conf
            - name: config-template
              mountPath: /opt/adguardhome/conf/AdGuardHome.yaml
              subPath: AdGuardHome.yaml
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Taipei
        - name: adguard-data
          persistentVolumeClaim:
            claimName: adguard-pvc
        - name: adguard-config
          emptyDir: {} # This creates a writable volume
        - name: config-template
          configMap:
            name: adguard-config
      restartPolicy: Always

