apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: adguard
resources:
  - namespace.yaml
  - pv.yaml
  - pvc.yaml
  - configmap.yaml
  - secret.yaml
  - service.yaml
  - deployment.yaml
