apiVersion: v1
kind: Secret
metadata:
  name: adguard-secret
  namespace: adguard
type: Opaque
data:
  # Example:
  # password: {{ .Values.password | b64enc }}
  users.yaml: dXNlcnM6CiAgLSBuYW1lOiBhZG1pbgogICAgcGFzc3dvcmQ6ICJCYyExNDcyODIwIgo=
---

