apiVersion: v1
kind: Service
metadata:
  name: adguard-home
  namespace: adguard
  labels:
    app: adguard
  annotations:
  promethues.io/scrape: "true"
  promethues.io/port: "30517"
spec:
  selector:
    app: adguard-home
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: web-admin
      protocol: TCP
      port: 3000
      targetPort: 3000
    - name: web-interface
      protocol: TCP
      port: 80
      targetPort: 80
    - name: dns-udp
      protocol: UDP
      port: 53
      targetPort: 53
    - name: dns-tcp
      protocol: TCP
      port: 53
      targetPort: 53
---

