apiVersion: apps/v1
kind: Deployment
metadata:
  name: tailscale
  namespace: tailscale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tailscale
  template:
    metadata:
      labels:
        app: tailscale
    spec:
      serviceAccountName: tailscale
      containers:
        - name: tailscale
          image: tailscale/tailscale:latest
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE
          env:
            - name: TS_AUTHKEY
              valueFrom:
                secretKeyRef:
                  name: tailscale-auth
                  key: TS_AUTHKEY
            - name: TS_KUBE_SECRET
              value: "tailscale-auth"
            - name: TS_USERSPACE
              value: "false"
            - name: TS_AUTH_ONCE
              value: "true"
            - name: TS_STATE_DIR
              value: "/var/lib/tailscale"
          volumeMounts:
            - name: devnet
              mountPath: /dev/net/tun
            - name: varlib
              mountPath: /var/lib
      volumes:
        - name: devnet
          hostPath:
            path: /dev/net/tun
        - name: varlib
          emptyDir: {}
