apiVersion: apps/v1
kind: Deployment
metadata:
  name: tailscale
  namespace: tailscale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tailscale
  template:
    metadata:
      labels:
        app: tailscale
    spec:
      serviceAccountName: tailscale
      containers:
        - name: tailscale
          image: tailscale/tailscale:latest
          securityContext:
            privileged: true # Required for enabling IP forwarding
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE
          env:
            - name: TS_AUTHKEY
              valueFrom:
                secretKeyRef:
                  name: tailscale-auth
                  key: TS_AUTHKEY
            - name: TS_KUBE_SECRET
              value: "tailscale-auth"
            - name: TS_USERSPACE
              value: "false"
            - name: TS_AUTH_ONCE
              value: "true"
            - name: TS_STATE_DIR
              value: "/var/lib/tailscale"
          command:
            - sh
            - -c
            - |
              # Enable IP forwarding
              sysctl -w net.ipv4.ip_forward=1
              sysctl -w net.ipv6.conf.all.forwarding=1

              # Disable GRO for optimal forwarding performance
              ethtool -K eth0 gro off

              # Start tailscaled
              tailscaled &

              # Advertise routes and bring Tailscale up
              tailscale up \
                --advertise-routes=10.0.0.0/24 \
                --accept-dns=true

              # Keep the container running
              tail -f /dev/null
          volumeMounts:
            - name: devnet
              mountPath: /dev/net/tun
            - name: varlib
              mountPath: /var/lib
      volumes:
        - name: devnet
          hostPath:
            path: /dev/net/tun
        - name: varlib
          emptyDir: {}
