apiVersion: v1
kind: ServiceAccount
metadata:
  name: tailscale
  namespace: tailscale

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: taildcale
  namespace: taildcale

rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["tailscale-auth"]
    verbs: ["get", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tailscale
  namespace: tailscale
subjects:
  - kind: ServiceAccount
    name: taildcale
roleRef:
  kind: Role
  name: tailscale
  apiGroup: rbac.authorization.k8s.io/v1
