apiVersion: v1
kind: Secret
metadata:
  name: tailscale-auth
  namespace: tailscale
type: Opaque
data:
  TS_AUTHKEY: dHNrZXktYXV0aC1rWWo1OVI3RXoxMjFDTlRSTC1IOGlicWNFUHpoMUFva2JlM3VONWgxVnh6Tm9NZjcxbTU=
