apiVersion: v1
kind: Secret
metadata:
  name: tailscale-auth
  namespace: tailscale
type: Opaque
data:
  # You'll need to replace this with your actual auth key: echo -n "tskey-xxx" | base64
  auth_key: "dHNrZXkteHh4"
